#!/bin/bash
# generate-manifest.sh - scans ~/.claude/skills/ for SKILL.md files,
# writes a table of skills + descriptions to ~/.claude/SKILL_MANIFEST.md,
# and flags description pairs that share 3+ keywords.
# Pure bash. No Python, no LLM calls.

set -euo pipefail

SKILLS_DIR="$HOME/.claude/skills"
MANIFEST="$HOME/.claude/SKILL_MANIFEST.md"
TMP_DATA="$(mktemp)"
STOP_FILE="$(mktemp)"
trap 'rm -f "$TMP_DATA" "$STOP_FILE"' EXIT

# Stop words (newline-separated) to strip before comparing keywords
cat > "$STOP_FILE" <<'EOF'
the
a
an
is
are
was
were
be
been
being
have
has
had
does
did
will
would
could
should
may
might
must
shall
to
of
and
in
that
it
for
on
with
as
at
by
from
or
but
not
this
these
those
use
used
using
when
if
then
also
like
via
each
per
into
onto
over
under
about
other
another
such
any
all
some
new
user
users
code
claude
skill
skills
tool
tools
file
files
help
EOF

# Parse frontmatter from every SKILL.md (take FIRST name/description only)
while IFS= read -r -d '' skill_md; do
    name=""
    desc=""
    in_fm=0
    fm_count=0
    while IFS= read -r line; do
        if [[ "$line" == "---" ]]; then
            fm_count=$((fm_count + 1))
            if [ "$fm_count" -eq 1 ]; then in_fm=1; continue; fi
            if [ "$fm_count" -eq 2 ]; then break; fi
        fi
        [ "$in_fm" -eq 1 ] || continue
        if [ -z "$name" ] && [[ "$line" =~ ^name:[[:space:]]*(.*)$ ]]; then
            name="${BASH_REMATCH[1]}"
        elif [ -z "$desc" ] && [[ "$line" =~ ^description:[[:space:]]*(.*)$ ]]; then
            desc="${BASH_REMATCH[1]}"
        fi
    done < "$skill_md"

    # Fall back to parent dir name
    if [ -z "$name" ]; then
        name="$(basename "$(dirname "$skill_md")")"
    fi
    [ -z "$desc" ] && desc="(no description)"

    # Strip surrounding quotes
    name="${name%\"}"; name="${name#\"}"
    desc="${desc%\"}"; desc="${desc#\"}"

    # Collapse tabs to spaces in desc so our TSV stays clean
    desc="${desc//$'\t'/ }"

    printf '%s\t%s\n' "$name" "$desc" >> "$TMP_DATA"
done < <(find "$SKILLS_DIR" -maxdepth 3 -type f -name "SKILL.md" -print0 2>/dev/null | sort -z)

# Sort by skill name for stable output
sort -t$'\t' -k1,1 "$TMP_DATA" -o "$TMP_DATA"

# Write the manifest
{
    echo "# Skill Manifest"
    echo "# Auto-generated by generate-manifest.sh — DO NOT EDIT MANUALLY"
    echo "# Last sync: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo
    echo "| Skill | Description |"
    echo "|-------|-------------|"
    while IFS=$'\t' read -r n d; do
        if [ ${#d} -gt 80 ]; then
            d="${d:0:77}..."
        fi
        d_esc="${d//|/\\|}"
        echo "| $n | $d_esc |"
    done < "$TMP_DATA"

    echo
    echo "## Overlap Warnings"
    echo

    # Build keyword files (one per skill) indexed by line number
    KW_DIR="$(mktemp -d)"
    line_num=0
    while IFS=$'\t' read -r n d; do
        line_num=$((line_num + 1))
        echo "$n" > "$KW_DIR/$line_num.name"
        echo "$d" \
            | tr '[:upper:]' '[:lower:]' \
            | tr -cs 'a-z0-9' '\n' \
            | awk 'length($0) > 3' \
            | sort -u \
            | grep -vxFf "$STOP_FILE" \
            > "$KW_DIR/$line_num.kw" || true
    done < "$TMP_DATA"
    total=$line_num

    overlap_found=0
    i=1
    while [ $i -le $total ]; do
        j=$((i + 1))
        while [ $j -le $total ]; do
            shared_count=$(comm -12 "$KW_DIR/$i.kw" "$KW_DIR/$j.kw" | wc -l | tr -d ' ')
            if [ "$shared_count" -ge 3 ]; then
                name_i=$(cat "$KW_DIR/$i.name")
                name_j=$(cat "$KW_DIR/$j.name")
                shared_words=$(comm -12 "$KW_DIR/$i.kw" "$KW_DIR/$j.kw" | tr '\n' ',' | sed 's/,$//; s/,/, /g')
                echo "- \`$name_i\` ↔ \`$name_j\` share $shared_count keywords: $shared_words"
                overlap_found=1
            fi
            j=$((j + 1))
        done
        i=$((i + 1))
    done

    rm -rf "$KW_DIR"

    if [ "$overlap_found" -eq 0 ]; then
        echo "_No description overlaps detected._"
    fi
} > "$MANIFEST"

echo "Wrote $MANIFEST ($(wc -l < "$MANIFEST" | tr -d ' ') lines, $total skills)"
