#!/bin/bash
# Compound knowledge synthesis
# Reads learnings/, patterns/, decisions/ and writes COMPOUND_KNOWLEDGE.md
# via a headless `claude -p` call. Runs only when new entries exist since
# the last synthesis, unless --force is passed.
#
# Triggered at the end of session-finalizer.sh (every 5 min via launchd),
# or manually via the /synthesize-knowledge skill.

set -euo pipefail

KNOWLEDGE_ROOT="${AGENTIC_OS_VAULT:-$HOME/Documents/agentic-os}/00_System/knowledge"
LEARNINGS="$KNOWLEDGE_ROOT/learnings"
PATTERNS="$KNOWLEDGE_ROOT/patterns"
DECISIONS="$KNOWLEDGE_ROOT/decisions"
COMPOUND="$KNOWLEDGE_ROOT/COMPOUND_KNOWLEDGE.md"
LOCK="/tmp/claude-synthesize-knowledge.lock"
LOG="$HOME/.claude/logs/synthesize-knowledge.log"

mkdir -p "$(dirname "$LOG")"

FORCE=false
[ "${1:-}" = "--force" ] && FORCE=true

# Prevent concurrent runs
if [ -f "$LOCK" ]; then
    lock_age=$(( $(date +%s) - $(stat -f %m "$LOCK" 2>/dev/null || echo 0) ))
    if [ "$lock_age" -lt 600 ]; then
        echo "[$(date)] Another synthesis in progress (lock $lock_age s old). Exiting." >> "$LOG"
        exit 0
    fi
fi
trap 'rm -f "$LOCK"' EXIT
touch "$LOCK"

# Find newest source file mtime
newest_source=$(find "$LEARNINGS" "$PATTERNS" "$DECISIONS" -type f -name "*.md" -print0 2>/dev/null \
    | xargs -0 stat -f "%m" 2>/dev/null | sort -rn | head -1)

if [ -z "$newest_source" ]; then
    echo "[$(date)] No source files yet. Exiting." >> "$LOG"
    exit 0
fi

# Compare to last synthesis time
if ! $FORCE && [ -f "$COMPOUND" ]; then
    last_syn=$(stat -f "%m" "$COMPOUND" 2>/dev/null || echo 0)
    if [ "$newest_source" -le "$last_syn" ]; then
        echo "[$(date)] No new knowledge since last synthesis. Skipping." >> "$LOG"
        exit 0
    fi
fi

source_count=$(find "$LEARNINGS" "$PATTERNS" "$DECISIONS" -type f -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
echo "[$(date)] Synthesizing compound knowledge from $source_count sources..." >> "$LOG"

# Build the prompt
read -r -d '' PROMPT <<'EOF' || true
You are synthesizing compound knowledge from a personal knowledge vault.

Read every .md file in these three directories:
  ${AGENTIC_OS_VAULT:-$HOME/Documents/agentic-os}/00_System/knowledge/learnings/
  ${AGENTIC_OS_VAULT:-$HOME/Documents/agentic-os}/00_System/knowledge/patterns/
  ${AGENTIC_OS_VAULT:-$HOME/Documents/agentic-os}/00_System/knowledge/decisions/

Also read the existing ${AGENTIC_OS_VAULT:-$HOME/Documents/agentic-os}/00_System/knowledge/COMPOUND_KNOWLEDGE.md if it exists. Preserve its existing themes and fold new entries into them rather than re-theming from scratch. Stable themes across runs matter.

Then OVERWRITE COMPOUND_KNOWLEDGE.md with this exact structure:

<!-- AUTO-GENERATED by synthesize-knowledge.sh — do not edit manually.
     Edits will be overwritten on the next synthesis run. -->
---
last_synthesized: <ISO 8601 UTC timestamp, e.g. 2026-04-28T13:00:00Z>
sources_count: <total number of source .md files>
themes_count: <number of ## sections you wrote>
---

# Compound Knowledge

Auto-synthesized from `learnings/`, `patterns/`, and `decisions/`.
Each theme grows over time as new entries are extracted.

## <Theme Name>
- <one-line insight> (<type> YYYY-MM-DD, source: <filename without date prefix, without .md>)
- ...

Rules:
- Infer themes semantically from content (e.g., "Design System Prototyping", "Session & Memory Management", "Data Safety"). Do not hardcode.
- Include learnings, patterns, AND decisions — all three compound together.
- One line per insight. No paragraphs.
- <type> is `learned`, `pattern`, or `decided`.
- If a newer entry contradicts or updates an older one, keep BOTH. Append "(superseded YYYY-MM-DD by <new-source>)" to the old one.
- Do not modify or delete any files in learnings/, patterns/, or decisions/.
- Do not write anything except COMPOUND_KNOWLEDGE.md.

Write the file and stop. No explanation, no summary output.
EOF

# Run Claude headless. Narrow tool allowlist - no shell, no network.
# Uses the user's default model (Opus alias is set in their shell).
claude -p "$PROMPT" \
    --allowedTools "Read" "Write" "Glob" "Grep" \
    --add-dir "$KNOWLEDGE_ROOT" \
    >> "$LOG" 2>&1 \
    || { echo "[$(date)] claude -p failed (exit $?)" >> "$LOG"; exit 0; }

if [ -f "$COMPOUND" ]; then
    echo "[$(date)] Synthesis complete. $source_count sources -> COMPOUND_KNOWLEDGE.md" >> "$LOG"
else
    echo "[$(date)] Warning: claude -p exited 0 but COMPOUND_KNOWLEDGE.md not written." >> "$LOG"
fi
